




title: AI Experiments
email:
description: >- # this means to ignore newlines until "baseurl:"
  My experiments with AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcinnis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: waiting4agi
github_username:  marcinnis

# Build settings
theme: minima
#theme: Hacker
#theme: Architect
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#remote-theme: dark-poole
#remote_theme: chesterhow/tale
#remote_theme: "dracula/gh-pages"

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-paginate
#  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
